spring:
  config:
    import: application-aws.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
